{% set name = "jina" %}
{% set version = "2.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha: 0ff0f811c5c34c5b07efbb64cfc64ef37c9d9a77d4052a49b928014e44e93c3c

build:
  number: 0

outputs:
- name: jina-core
  build:
    entry_points:
    - jina = cli:main
    - jinad = daemon:main
    script: python -m pip install . --no-deps -vv
  test:
    requires:
    - pip
    imports:
    - jina
    commands:
    - pip check
    - jina --version
  requirements:
    host:
    - python >=3.7
    - pip
    run:
    - python
    - numpy
    - grpcio >=1.33.1
    - pyzmq >=17.1.0
    - tornado >=5.1.0
    - pyyaml >=5.3.1
    - protobuf >=3.13.0
- name: jina-perf
  test:
    requires:
    - pip
    imports:
    - jina
    commands:
    - pip check
    - jina --version
  requirements:
    host:
    - python >=3.7
    - pip
    run:
    - python >=3.7
    - {{ pin_subpackage('jina-core', exact=True) }}
    - uvloop
    - lz4 <3.1.2
- name: jina
  test:
    requires:
    - pip
    imports:
    - jina
    commands:
    - pip check
    - jina --version
  requirements:
    host:
    - python >=3.7
    - pip
    run:
    - python >=3.7
    - {{ pin_subpackage('jina-core', exact=True) }}
    - uvloop
    - cryptography
    - aiostream
    - uvicorn[standard] >=0.14.0
    - lz4 <3.1.2
    - python-multipart
    - pathspec
    - docker-py
    - aiofiles
    - aiohttp
    - requests
    - filelock
    - pydantic
    - websockets
    - fastapi
    - rich
- name: jina-daemon
  test:
    requires:
    - pip
    imports:
    - jina
    commands:
    - pip check
    - jina --version
  requirements:
    host:
    - python >=3.7
    - pip
    run:
    - python >=3.7
    - {{ pin_subpackage('jina-core', exact=True) }}
    - uvloop
    - fluent-logger
    - cryptography
    - uvicorn[standard] >=0.14.0
    - aiostream
    - lz4 <3.1.2
    - websockets
    - pathspec
    - fastapi
    - aiofiles
    - aiohttp
    - requests
    - filelock
    - pydantic
    - python-multipart
    - docker-py
    - rich
- name: jina-demo
  test:
    requires:
    - pip
    imports:
    - jina
    commands:
    - pip check
    - jina --version
  requirements:
    host:
    - python >=3.7
    - pip
    run:
    - python >=3.7
    - {{ pin_subpackage('jina-core', exact=True) }}
    - cryptography
    - lz4 <3.1.2
    - pytorch-cpu >=1.1.0
    - aiohttp
    - filelock
    - rich
    - uvicorn[standard] >=0.14.0
    - pathspec
    - python-multipart
    - docker-py
    - aiostream
    - Pillow
    - aiofiles
    - pydantic
    - fastapi
    - torchvision >=0.3.0
    - uvloop
    - transformers >=2.6.0
    - requests
    - websockets

about:
  home: https://github.com/jina-ai/jina/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: Jina is the cloud-native neural search framework for any kind of data
  doc_url: https://docs.jina.ai

extra:
  recipe-maintainers:
  - tadejsv
  - maateen
  - nan-wang
  - hanxiao
